--- #YAML:1.0
name:               Template-DBI
version:            2.65
abstract:           Template interface to the DBI module
author:
    - Andy Wardley <abw@wardley.org>, Jens Rehsack <rehsack@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    MLDBM:           0
    SQL::Statement:  1.28
requires:
    DBI:       1.612
    perl:      5.008
    Template:  2.22
resources:
    license:      http://dev.perl.org/licenses/
    MailingList:  mailto:templates@template-toolkit.org
    repository:   svn://svn.tt2.org/tt/Template-DBI/trunk/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    MLDBM:                0
    SQL::Statement:       1.28
    threads::variable::reap:  0.05
